# Generated by Django 2.0.9 on 2018-12-04 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phase', models.IntegerField(choices=[(0, 'Ranked'), (1, 'Playoffs')], default=0)),
                ('result', models.IntegerField(choices=[(0, '2-0'), (1, '2-1'), (3, '0-2'), (2, '1-2')])),
                ('player1_rating_change', models.IntegerField(blank=True, null=True)),
                ('player2_rating_change', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo_rating', models.IntegerField(db_index=True, default=1000)),
                ('min_rating', models.IntegerField(null=True)),
                ('max_rating', models.IntegerField(null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_results', to='app.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('placement_games', models.IntegerField(default=5)),
                ('playoff_data', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='playerresults',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_results', to='app.Season'),
        ),
        migrations.AddField(
            model_name='game',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player1', to='app.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player2', to='app.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='app.Season'),
        ),
        migrations.AlterUniqueTogether(
            name='playerresults',
            unique_together={('season', 'player')},
        ),
    ]
