# Generated by Django 2.0.9 on 2018-12-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerresults',
            name='max_rating',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='playerresults',
            name='min_rating',
            field=models.IntegerField(default=1000),
        ),
    ]
