# Generated by Django 2.0.9 on 2018-12-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181204_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='result',
            field=models.IntegerField(choices=[(0, '2-0'), (1, '2-1'), (3, '0-2'), (2, '1-2'), (4, '3-0'), (5, '3-1'), (6, '3-2'), (7, '2-3'), (8, '1-3'), (9, '0-3')]),
        ),
    ]
