# Generated by Django 2.1.5 on 2019-02-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181213_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='playoff_data',
            field=models.TextField(blank=True),
        ),
    ]
